// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PQE6pANFE25T5nMmrwvwjhSNPYRfXSc',
    appId: '1:369151569036:android:ca1e03e7911a1a4e429fa9',
    messagingSenderId: '369151569036',
    projectId: 'samnangicecream-ddabe',
    storageBucket: 'samnangicecream-ddabe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxRNjcUyWJImkHOvp8uNl8BvcM4-n2sH8',
    appId: '1:369151569036:ios:54b8df62f88bf37e429fa9',
    messagingSenderId: '369151569036',
    projectId: 'samnangicecream-ddabe',
    storageBucket: 'samnangicecream-ddabe.firebasestorage.app',
    iosBundleId: 'com.example.samnangIceCreamRoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW14OuySSM5dfUr6d80eDEWPV6IFV4-rQ',
    appId: '1:369151569036:web:f97dfb7b8b760048429fa9',
    messagingSenderId: '369151569036',
    projectId: 'samnangicecream-ddabe',
    authDomain: 'samnangicecream-ddabe.firebaseapp.com',
    storageBucket: 'samnangicecream-ddabe.firebasestorage.app',
    measurementId: 'G-XW4EQNXQ2P',
  );
}
